### PR TITLE
update for 1.10

### PR DESCRIPTION
**Pull request by oscardssmith**
https://github.com/JuliaLang/julia/pull/48766 makes it so `retrieve_code_info` takes in a worldage, and dramatically simplifies construction of .

### CODE REVIEW

**Comment by oxinabox** [comment]
Also needs to actually define an overload of `__overdub_generator__` which accepts a world-age etc.

**Comment by oscardssmith** [comment]
This still has 1 erroring test and 2 failing but that predates this PR. 1.10 now works as well as 1.9.

**Comment by oxinabox** [comment]
Can we mark those tests as broken so we can merge this?

They don't look important, but I am not sure.

**Comment by oscardssmith** [comment]
I figure they're not that important given that they're also broken in Julia 1.9

**Comment by oscardssmith** [comment]
Unfortunately the errors on 1.9 were actually hiding errors that were happening later on in the code. commit incoming.

**Comment by oxinabox** [comment]
Looking at the last 2 failures.
It looks like they both should be handled with:
```
if VERSION>v"1.9"
    @test ...
else
   @test ...
```
because I think both old and new answer is correct and it just represents a nonsemantic change in the internals.
The numbers are all the same.
just the addition of a `core._apply` operation.

**Review by vchuravy — APPROVED** [review]

**Pull request merged**
